all:
  hosts:
    web:
      ansible_ssh_host: ec2-18-140-2-37.ap-southeast-1.compute.amazonaws.com
      ansible_port: 22
      ansible_user: ec2-user
      ansible_ssh_private_key_file: /home/bom/key/ansible-31052565.pem